### ISSUE TITLE
我这运行出现了问题 delphixe10.1

### ISSUE THREAD

**Issue by yupor5** [pony5551/PnHttpSysServer#1]
我这运行出现了问题 delphixe10.1
function AtomicOr(var Dest: Integer; const AMask: Integer): Integer; inline;
var
  I: Integer;
begin
  repeat
    Result := Dest;
    I := Result or AMask;
  until AtomicCmpExchange(Dest, I, Result) = Result;
end;

constructor TQSimpleLock.Create;
begin
  inherited;
  FFlags := 0;
end;

procedure TQSimpleLock.Enter;
begin
  while (AtomicOr(FFlags, $01) and $01)<>0 do
    begin
      {$IFDEF UNICODE}
      TThread.Yield;
      {$ELSE}
      SwitchToThread;
      {$ENDIF}
    end;
end;

提示
[dcc64 Error] lib.PnLocker.pas(87): E2441 Inline function declared in interface section must not use local symbol 'AtomicOr'

**Comment by pony5551** [comment]
这个是TQSimpleLock的问题，你可以取消这部分代码，使用TMonitor的锁就可以

当然这个自旋锁可以换成系统的TSpinLock

这两天我更新一下

**Comment by pony5551** [comment]
问题已经修正
